### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by abelRoland** [CodeYourFuture/html-css-git-exercises#89]
I believe that you change your folder structure, because now all the relative paths for the stylesheets and images are not working.

**Comment by NateWr** [comment]
Are you running the exercises according to the instructions, by using `npm run <exercise-number>`? When run this way, the links should work.

**Comment by abelRoland** [comment]
Sorry, you are right, I just clone and start to work on it. I was not running npm. My mistake. I'll close the issue and the pull request. Thanks.

**Comment by NateWr** [comment]
No worries! Thanks for looking into it. :+1:
